<?php

// configuration pour le rallye 2023 !

$rallyeContent = array (
//  CODE                 NOM                                            PUBLIÉ      MOT DE PASSE     
"E00hIMu5aHC" => array(  "Enigme mystère",				        		true,      	'$2y$10$8rgkRsDPsVn6o7kU0BTAgu/ai.mU4iXTmDYZi7ZK0EXEt3HiStcy.'),    
"E01stagadaz" => array(  "Tous à l'appel",                          	true,       '$2y$10$hx9uQYAc.8N7yR3VHPQkFeFYWT.paPQ5EIK8RmHLbJdVfVNVihBFq'),    
"E02sNRzdvwG" => array(  "Les gommettes", 	                    		true,      	'$2y$10$cbuyOHHtF8N4Ag5JIJerTOxvD3.j9.RbXLbkcI1nvnSgEu9X4/rUW'),    
"E03LzstgTKf" => array(  "Le nouveau copain",                      		true,       '$2y$10$.GIgbUL98UAffbusy5QpiuW7ML5chq3FizXuWqTGT27F9sCWMf9ri'),        
"E04cZKxsne4" => array(  "La cour d'école",                           	true,       '$2y$10$6xvNdBz/hK0PudDALieNPuxkGHJLj1aWH1CeD2hXgsbUSeC4RtZWa'),    
"E05re7adq9d" => array(  "Mémoires d'une enseignante",        			true,       '$2y$10$zJBZzylHam0lyF3oCoqZA.4.f4/fnyvNmNo7mrYzrA.mohdyh5RUW'),         
"E06q4BaqyWM" => array(  "Leçon de choses",                       		true,       '$2y$10$M4pA.JWXVSpMKrjuwH.w7.vwAwwyCHByy3fWueIXvRkXyyK6Wc2z6'),
"E07nGzqduHZ" => array(  "Le cours élémentaire",                  		true,       '$2y$10$GLnssTIFrPmE7r8nEEwIfu6jpnN.38cLSqDosDBcP8jOhYSgJxbg.'),    
"E08FfqtgBBd" => array(  "CM2 : évaluation de niveau",          		true,       '$2y$10$z9PykEz3vImPFan.RwtodeiA6VS43OAyk8oseHxUWABWBTxSaZMDi'),    
"E09wwTfbyCw" => array(  "Les gorilles selon Toto",                		true,       '$2y$10$uSLnJD0Nur2VlylHd1EQJOwRjGYYy5nqFpaO8IzN2n4M5JfDCWvs6'),
"E10jt7qsRSM" => array(  "L'école buissonnière",                   		true,       '$2y$10$Yn55tdpJuq.mklTHtOHE9.LhPYMvHaacp4e6O/AniPnqLuhMkDLh2'),        
"E11KYLgghGY" => array(  "Nombres",                   					true,       '$2y$10$6hRXFYp1jt49nQ92jLrDyuh4pjawsxLgbGcq313TBZcBMzTnRLotK'),    
"E12Ycdxxwzc" => array(  "L'échange scolaire",                     		true,       '$2y$10$rjWvx1C74co0I7WlfA7e9e1YMoJbCnrk3hUzz83UqJ9XR8Z33f1va'),
"E13mS3vgRcj" => array(  "Joe Dalton, au tableau !",               		true,       '$2y$10$XisjOhn65pNf4p0.fnppLe.Tfqj4x0kYw.myHEe3SC8bp8SEgUcPO'),       
"E14D8jytUts" => array(  "Géométries",                			 		true,       '$2y$10$3VYLzc0hjUukHHJyKcJ.DOC.NZvAQqDcs4LQbm6lAyo5vVlwKRhfu'),    
"E15FqqndN6F" => array(  "La classe verte",                      		true,       '$2y$10$jVW2G05DNhUz6L85mO2TN.loVzLc5lS1ZKMKrV3iE4R7n.CU.XInm'),    
"E16fcGyrAwF" => array(  "Le bulletin scolaire",                    	true,       '$2y$10$M5fhhkv5K7pTdDTlZZOGguTNq85QQxMfHHU/qIPrj5tjahTs1RC02'), 
"E17JczssJqh" => array(  "Un héros méconnu",                     		true,       '$2y$10$qvqiqtrV.ycVxVuSIV6druJmNbhr.LIAgqmnMXHhMElIs29r5cW/q'), 
"E18ucgyhV8F" => array(  "Conseils pour le bac français",       		true,       '$2y$10$yck71dhTU5vdrNUhMQCYueDnfM0dPJPgYruzifQtXONrtVZf4iCtm'), 
"E19NNjxcs3K" => array(  "L'épreuve de Maths App'",               		true,       '$2y$10$65SL5Pn4YqvpCJLbPuEh6.TrEoyHOLIycagsqt2zTYwlMsSbJDr2q'), 
"E20EKsaz647" => array(  "Situations d'influence",                		true,       '$2y$10$AxtyGZqyYsoCMsE68KkRku2A0mZJH5hXlbenXpFEqeTISTcWVhsTS'), 

"P01SBCnjwqc" => array(  "Cursus scolaire",                             true,       '$2y$10$3csHY/MxCqKd4FaMGimCH.IczA0izA0bUx1Km4Wkyq4JD8/QoSj9.', false),    
"P021PdMzs2z" => array(  "Charlemagne (partie 1)",                      true,       '$2y$10$.b4MLfkrfYSkm7NMNVV2Cu5nL6V/8JIAIOBOuedTvDYjA/kB7UygC', false),    
"P022JziaBUU" => array(  "Charlemagne (partie 2)",                      true,       '$2y$10$Cmn2j/auAlw2KlaNETXVw.AG0e9mOpEUB4XvAxT6FOMsbRP6xeV2S', true),    
"P03m8Yuiq6p" => array(  "Lamartine",                                   true,       '$2y$10$taEmBpiMkZxRLawsDJpHSuQ5fWG2XopgMuMHeAXpetnN8kWUOh48O', false),        
"P04LzucfawE" => array(  "Buffon",           					        true,       '$2y$10$IiHyajY/Xf9pG1hI/Vb0/.l53yf8j.TR4t3OT81u8wjhPnwV0jSHO', false),    
"P051ubbhzh4" => array(  "Mémoire (partie 1)",                          true,       '$2y$10$T9k3B3mjIvn/q8ciwLPu8OLkAcNyckIKw4SKlS05IoVkXWSb3fdNi', false),         
"P052H6dGHzL" => array(  "Mémoire (partie 2)",                          true,       '$2y$10$e.s7ggkIT3e7OUb6g0Jpre/1J6cSIDAKrP9Pti1Tr16QW.WwBQV0u', true),         
"P06CT2VzzxK" => array(  "Raspail",                                     true,       '$2y$10$qNvUZMJUxNNZAK.BCTWQAeudka5MrTVPPABjJhEEPjiveV35Gehbi', false),
"P07Q6Anht7A" => array(  "Examen",                                      true,       '$2y$10$AVkdraNCjlhsoyxu/WcxcOc8./bgoypeU.DaVb7iaDRL66RxxTgc6', false),    
"P08NFeyuhZb" => array(  "Campus Nation",                               true,       '$2y$10$W2OlbkzkWSG6g8xBwo4n7OPoUSdy5hZDROv2qA.tHNnG9GsNLR4iK', false),    
"P09RKJsxLcH" => array(  "La balade des carabins",                      true,       '$2y$10$QPf1rttufFYxeIZhmDaWP..kFAkqntAtWQytlHF0/GoUG.ElnDf/S', false),     
"P10HRuHuaCo" => array(  "Parcours démat'",		                     	true,       '$2y$10$ljW4oK.ywv7ISoZ/d2QiGuIm4FsCio39UFps6hRoqLhG1/508Tpwa', false),     
);

// liste des réponses pré-enregistrées pour certains mauvais mots de passe
$mauvais_mdp = array (
    "TEST"                           => array(false,     		"Tout fonctionne correctement, vous pouvez commencer !"),
    "FAUX"                           => array(false,     		"Non, et en même temps vous auriez pu vous en douter..."),
    "MAUVAISEREPONSE"                => array(false,     		"Non, et en même temps vous auriez pu vous en douter..."),
    "BONNEREPONSE"                   => array(false,     		"Hum... comment dire. Ça valait le coup d'essayer c'est sûr !"),
    "ECOLE"                          => array(false,     		"C'est en effet le thème. Mais ce n'est pas ce qu'on vous demande !"),
    "LECOLE"                         => array(false,     		"C'est en effet le thème. Mais ce n'est pas ce qu'on vous demande !"),
    "REPONSE"                        => array(false,     		"Oui vous avez compris... c'est bien là qu'il faut mettre la réponse. Et maintenant au boulot !"),
    "LECON"                          => array(false,     		"Heureusement qu'il y a la cédille, n'est-ce pas ?..."),
	"PERSONNE"                       => array('E00hIMu5aHC',	"Euh... Vous vous appelleriez pas Polyphème, par hasard ?"),
    "YOUKI"                          => array('E00hIMu5aHC',	"Puisqu'on vous dit que c'est pas lui !"),
	"LEYOUKI"                        => array('E00hIMu5aHC',	"Puisqu'on vous dit que c'est pas lui !"),
    "PASLEYOUKI"                     => array('E00hIMu5aHC',	"Effectivement, c'est pas lui ! Mais qui, alors ?"),   
    "MOI"                            => array('E00hIMu5aHC',	"Pas du tout!"),
    "QUI"                            => array('E00hIMu5aHC',	"C'est précisément la question qu'on vous pose !"),
	"CHARLEMAGNE"                    => array('E00hIMu5aHC',	"Ca valait le coup d'essayer, hein ? Mais ça aurait été trop facile..."),
	"JULESFERRY"                     => array('E00hIMu5aHC',	"Ca valait le coup d'essayer, hein ? Mais ça aurait été trop facile..."),
	"JACKLANG"                       => array('E00hIMu5aHC',	"Ca valait le coup d'essayer, hein ? Mais ça aurait été trop facile..."),
    "KLEIN"                          => array('E04cZKxsne4',	"Vous avez l'oeil, c'est bien, mais il y a encore du boulot... Continuez !"),
	"LINSTIT"                        => array('E04cZKxsne4',	"Pas mal, vous chauffez, mais l'exercice n'est pas encore fini... Continuez !"),
	"RACINE"                         => array('E05re7adq9d',	"Hmmm... Il y a de l'idée. Je t'en ai dit assez pour te tirer d'erreur"),
	"DANNEMOIS"                      => array('E07nGzqduHZ',	"Pas mal, vous chauffez, mais l'exercice n'est pas encore fini... Continuez !"),
    "DIAGONALES"                     => array('E08FfqtgBBd',	"Pas mal, vous avez atteint le niveau 1 mais l'exercice n'est pas encore fini... Continuez !"),
	"ANE"                            => array('E08FfqtgBBd',	"C'était pourtant bien parti, mais là c'est vraiment une fausse piste !"),
    "MARIAMONTESSORI"                => array('E09wwTfbyCw',	"Vous y êtes presque : la bonne réponse tient en un mot"),
    "METHODEMONTESSORI"              => array('E09wwTfbyCw',	"Vous y êtes presque : la bonne réponse tient en un mot"),
    "COLLEGE"                        => array('E12Ycdxxwzc',	"Il y a de l'idée, mais c'est l'autre"),
    "PONTDELUNIVERSITE"              => array('E12Ycdxxwzc',	"Vous y êtes presque : la bonne réponse tient en un mot"),
    "HYPOTHENUSE"                    => array('E14D8jytUts',	"Il y a trop de H là-dedans : les spécialistes appellent ça une hypercorrection étymologiquement injustifiée. Réessayez sans !"),
    "CONJONCTIONDECOORDINATION"      => array('E15FqqndN6F',	"Pas mal, vous chauffez, mais l'exercice n'est pas encore fini... Continuez !"),
    "MAISOUESTDONCORNICAR"           => array('E15FqqndN6F',	"Attention, il y a un intrus... Réessayez après lui avoir donné une bonne correction !"),
); 

// liste des réponses toutes faites pour les mauvais mots de passe qui ne sont pas ci-dessus
$wrong = array (
    "Désolé, mais ce n'est pas la bonne réponse :(",
    "Oups, raté !",    
    "Sacrée imagination... mais non, ce n'est pas ça.",           
    "Non... essayez autre chose ?",    
    "Non, désolé :(",
    "Bien essayé... mais c'est non !",
    "Euh... non !",
    "Comment vous dire ?... c'est non.",
    "Non, ce n'est pas ça. Et vous me copierez cent fois : Je ne dois pas essayer n'importe quelle réponse sur le site du rallye.",
    "Non, ce n'est pas ça. Il y avait sans doute de l'idée, mais manifestement pas la bonne",
    "Quel dommage ! Ce n'est pas ça !",
    "Non, ce n'est pas ça. Patience et longueur de temps font plus que force ni que rage"	,
	"Désolé, mais non...",
	"Non, ce n'est pas ça. Ne désespérez pas, l'inspiration finira par venir...",
	"Non, ce n'est pas ça. N'oubliez pas que vous pouvez demander des indices...",
	"Non, ce n'est pas ça. Et si vous preniez le problème autrement ?",
	"Non, ce n'est pas ça. Le hasard fait bien les choses... mais pas ici",
	"Ah bon ? Vous croyez ? Eh bien non !",
	"Non, ce n'est pas ça. Il est à craindre qu'il y ait une erreur de raisonnement quelque part",
	"Non, ce n'est pas ça. 100% des gagnants ont tenté leur chance, mais ce n'est pas une loterie, ici !",
	"Non, ce n'est pas ça. À force d'essayer des trucs, ça finira sans doute par marcher. Ou pas...",
	"Non, ce n'est pas ça. C'est plus dur que ça en a l'air, n'est-ce pas ?",
	"Hélas, trois fois hélas, non !",
	"Ô Rage ! Ô Désespoir ! Ô Rallye ennemi ! N'ai-je donc tant vécu que pour cette infâmie ? (et non, c'est une mauvaise réponse...)",
	"Non, ce n'est pas ça. Ce serait sans doute plus facile si c'était un QCM, hein ?",
	"Non, ce n'est pas ça. Reprenons pas à pas",
	"Non, ce n'est pas ça. Errare humanum est...",
	"Non, ce n'est pas ça. Après une bonne nuit de sommeil, ça vous paraîtra peut-être plus facile",
	"Non, ce n'est pas ça. Et euh... quel rapport avec la choucroute ?",
	"Non, ce n'est pas ça. Tentez donc autre chose !",
	"Non, abordez donc le sujet sous un angle différent.",
	"Non, ce n'est pas ça. Revenez tenter autre chose lorsque vous serez plus inspiré.",
	"Non, mais je suis sûr que vous n'y croyiez pas vraiment vous-même, si ?",
	"Non. Que diriez-vous d'essayer une autre énigme si celle-ci vous résiste ?",
	"Expérience est le nom que nous donnons à nos erreurs (Oscar Wilde). Et non désolé, c'est une mauvaise réponse...",
	"Quel homme est sans erreur ? (Voltaire). Et non désolé, c'est une mauvaise réponse...",
	"Je chéris ta personne et je hais ton erreur (Les Plaideurs). Et non désolé, c'est une mauvaise réponse...",
	"Une erreur originale vaut mieux qu'une vérité banale (Dostoïevski). Et non désolé, c'est une mauvaise réponse...",
	"Avoir des convictions ne garantit pas contre l'erreur (Lionel Jospin). Et non désolé, c'est une mauvaise réponse...",
	"La hâte engendre en tout l'erreur (Hérodote). Et non désolé, c'est une mauvaise réponse...",
	"Nul doute : l'erreur est la règle : la vérité est l'accident de l'erreur (Georges Duhamel). Et non désolé, c'est une mauvaise réponse...",
	"La vérité sort plus facilement de l’erreur que de la confusion (Francis Bacon). Et non désolé, c'est une mauvaise réponse...",
	"La réalité ne pardonne pas une seule erreur à la théorie (Léon Trotski). Et non désolé, c'est une mauvaise réponse...",
	"L'erreur n'annule pas la valeur de l'effort accompli (Proverbe africain). Et non désolé, c'est une mauvaise réponse...",
	"Les intellectuels, plus ils sont intelligents, plus ils élaborent subtilement leur erreur (Jean-François Revel). Et non désolé, c'est une mauvaise réponse...",
	"L'erreur, comme le rire, est le propre de l'homme. Mais infiniment plus créatrice (Roland Topor). Et non désolé, c'est une mauvaise réponse...",
	"Les rivières ne se précipitent pas plus vite dans la mer que les hommes dans l'erreur (Voltaire). Et non désolé, c'est une mauvaise réponse...",
	"Jusqu’à présent, les hommes n’ont trouvé d’autre chemin vers la vérité que l’erreur (Nicolae Iorga). Et non désolé, c'est une mauvaise réponse...",
	"Celui qui agit peut commettre une erreur, celui qui n'agit pas en commet une de toute façon. Ah oui et non désolé, c'est une mauvaise réponse...",
	"Une erreur peut devenir exacte selon que celui qui l'a commise s'est trompé ou non (Pierre Dac). Et non désolé, c'est une mauvaise réponse...",
	"Le seul homme à ne jamais faire d'erreur est celui qui ne fait rien (Theodore Roosevelt). Et non désolé, c'est une mauvaise réponse...",
	"Chacun est sujet à faire des fautes, et à donner dans l'erreur (Proverbe danois). Et non désolé, c'est une mauvaise réponse..." ,
	"Non, ce n'est pas ça. Mais quelle idée bizarre !",
	"Non, ce n'est pas ça. Le recours aux cartomanciennes n'est pas recommandé",
	"Non, ce n'est pas ça. Mais 20/20 en créativité",
	"Non, ce n'est pas ça. Mais quelle imagination ! On n'y aurait jamais pensé ! D'ailleurs, c'est pas ce qu'on a trouvé." ,
	"Non, ce n'est pas ça. Tous les mots en rapport avec le thème ne sont pas forcément la réponse à une énigme. En tout cas, ce n'est pas la réponse à celle-là !",
	"Non, ce n'est pas ça. Non, mais sans doute avez-vous eu raison d'essayer quand même, histoire d'en avoir le coeur net...",
	"Non, ce n'est pas ça. Allez hop, petite séance de remue-méninges en équipe pour trouver une autre idée."
	);

?>