<?php

$questList = array (
	"gkehb0p5iv" => "La voie royale",
	"c12m85wqay" => "Au Bonheur des Dames",
	"7xp2fvpux7" => "A la recherche du temps perdu",
	"62ygx5pcx3" => "Clair comme de l'eau de roche",
	"rakl26jbu9" => "Le Triangle d'Or",
	"q6ktqn8n64" => "A la rencontre des artisans",
	"9nejv8ffgv" => "Soulier ou haut-de-forme",
	"q0gwu3mnhp" => "Un parfum de libertinage",
    "kq4set7edj" => "Hissez la grand-voile",
);

$enigmeList = array (
    //    NOM DE L'ENIGME                               QUESTIONNAIRE                           SOLUTION                 REPONSE
    array("Défense d'Ivoire",                           "A la rencontre des artisans",          "perle",                 ""),    
    array("Rimes Riches et Vers de grande valeur",      "Soulier ou haut-de-forme",             "lancia",                ""),    
    array("Faisons fi du Luxe",                         "A la recherche du temps perdu",        "nombredor",             ""),        
    array("Le bad boy brun et la rosée du matin",       "Clair comme de l'eau de roche",        "cristal",               ""),    
    array("Le mariage de la Barronne",                  "Le Triangle d'Or",                     "missdiorcherie",        ""),            
    array("Métronome",                                  "Un parfum de libertinage",             "louisvuitton",          ""),
    array("L'eau d'Issey",                              "Au Bonheur des Dames",                 "matisse",               ""),    
    array("Cérémonie des Césars",                       "A la recherche du temps perdu",        "iznogoud",              ""),    
    array("Le luxe à la française",                     "Clair comme de l'eau de roche",        "parcdestroisglands",    ""),
    array("Rendez-vous galant",                         "A la rencontre des artisans",          "pierreherme",           ""),        
    array("Au fil de Paris",                            "Au Bonheur des Dames",                 "omega",                 ""),    
    array("Récital A 4",                                "La voie royale",                       "petrus",                ""),
    array("Attrape-moi si tu peux",                     "A la rencontre des artisans",          "leblancmatraqueveranda",""),       
    array("En quête de luxe",                           "Le Triangle d'Or",                     "bristol",               ""),    
    array("L'or du Rhin",                               "A la recherche du temps perdu",        "hermes",                ""),    
    array("L'Ancien et le Nouveau",                     "Soulier ou haut-de-forme",             "jovitafoley",           ""),
    array("Jetlag",                                     "Soulier ou haut-de-forme",             "youkounkoun",           ""),
    array("L'Art du Luxe",                              "Un parfum de libertinage",             "pound",                 ""),
    array("A definir",                                  "Un parfum de libertinage",             "lakepalace",            ""), 
    array("Grand vin",                                  "Clair comme de l'eau de roche",        "baccarat",         	 ""),            
    array("Enigme mystère",                             "Hissez la grand-voile",                "lechampagnebollinger",  ""),            
);

// liste des réponses pré-enregistrées pour certains mauvais mots de passe
$mauvais_mdp = array (
    "champagne"         => array(false,     "Et non, cette réponse vaut une bulle !"),
    "vin"               => array(false,     "Non... et manifestement vous devriez arréter d'en abuser, il vous tourne la tête !"),
    "faux"              => array(false,     "Non, et en même temps vous auriez pu vous en douter..."),
    "mauvaisereponse"  => array(false,     "Non, et en même temps vous auriez pu vous en douter..."),
    "bonnereponse"     => array(false,     "Hum... comment dire. Ça valait le coup d'essayer c'est sûr !"),
    "reponse"           => array(false,     "Oui vous avez compris... c'est là qu'il faut mettre la réponse. Et maintenant au boulot !"),
    "bouton"           => array(false,     "Heu... c'était juste un exemple. Résolvez les vrais énigmes maintenant !"),
    "zara"              => array(false,     "Aie... on s'éloigne du luxe là !"),
    "h&m"               => array(false,     "Aie... on s'éloigne du luxe là !"),
    "tati"              => array(false,     "Aie... on s'éloigne du luxe là !"),
    "defursac"         => array(false,     "Et non... la griffe de l'homme mais pas celle du luxe !"),
    "oeufdefaberge"   => array(false,     "Vous ne voulez pas plutôt résoudre les énigmes au lieu de recopier le règlement ?"),
    "fibonacci"         => array(2,         "Hum... je vois que vous êtes sur une piste, mais là ça aurait été un peu facile, non ?"),
    "fibonacci"         => array(3,         "Non... mais vous y êtes presque !"),
    "missdior"         => array(5,         "Pas loin !"),
    "dior"         => array(5,         "Pas loin !"),
    "diorcherie"         => array(5,         "Pas loin !"),
    "lv"         => array(6,         "Pas loin !"),
    "vuitton"         => array(6,         "Pas loin !"),
    "tigre"         => array(7,         "Trop facile, cherchez encore !"),
    "baudelaire"         => array(7,         "C'est bien l'auteur, mais pas un fauve."),
    "leparcdestroisglands" => array(9,         "Allez, enlevez le déterminant au début et je vous l'accorde :)"),
    "troisglands"         => array(9,         "Pas loin !"),
    "jardin du luxembourg"         => array(9,         "Encore un (tout) petit effort !"),
    "emeraude"         => array(10,         "Oui ! Mais vous ne testez pas au bon endroit ... retournez voir les photos."),
    "henriiv"         => array(false,         "Roi de France et de Navarre, et plutôt bon lycée parisien... mais ce n'est pas ce que vous attendiez comme réponse n'est-ce pas ? Désolé ce n'est pas la bonne piste !"),
    "alpha"         => array(11,         "Encore un petit effort..."),
    "herculepoirot"         => array(12,         "Ça serait un peu facile non ?"),
    "hercule"         => array(12,         "Ça serait un peu facile non ?"),
    "poirot"         => array(12,         "Ça serait un peu facile non ?"),
    "leblancverandamatraque"         => array(13,         "Selon les règles du jeu, ce n'est pas le bon ordre ;)"),
    "verandamatraqueleblanc"         => array(13,         "Selon les règles du jeu, ce n'est pas le bon ordre ;)"),
    "verandaleblancmatraque"         => array(13,         "Selon les règles du jeu, ce n'est pas le bon ordre ;)"),
    "matraqueleblancveranda"         => array(13,         "Selon les règles du jeu, ce n'est pas le bon ordre ;)"),
    "matraqueverandaleblanc"         => array(13,         "Selon les règles du jeu, ce n'est pas le bon ordre ;)"),
    "meurice"         => array(14,         "Pas loin !"),
    "wagner"         => array(15,         "Ça serait un peu facile non ?"),
    "siegfried"         => array(15,         "Ça serait un peu facile non ?"),
    "lesfillesdurhin"         => array(15,         "Ça serait un peu facile non ?"),
    "tokyo"         => array(17,         "Ça serait un peu facile non ?"),
    "rome"         => array(17,         "Ça serait un peu facile non ?"),
    "ljubljana"         => array(17,         "Ça serait un peu facile non ?"),
    "londres"         => array(17,         "Ça serait un peu facile non ?"),
    "prague"         => array(17,         "Ça serait un peu facile non ?"),
    "moreau"         => array(18,         "C'est bien lui... mais ce n'est que le début."),
    "elgar"         => array(18,         "Vous avancez bien ! Vous en êtes à la moitié."),
    "pell"         => array(18,         "Bien vu, il y a quelque chose à creuser ici !"),
    "scaphandre"    => array(18,         "N'auriez-vous pas laissé des lettres de côté ?"),
    "gbp"         => array(18,         "Oui presque ! Quelle autre appellation moins technique ?"),
    "livre"         => array(18,         "En version originale s'il vous plait !"),
    "livresterling"         => array(18,         "En version originale s'il vous plait !"),
    "poundsterling"         => array(18,         "Oubliez le sterling !"),
    "climat"         => array(false,         "Oui vous avez raison, il fait un peu froid en ce moment, je vais chercher un  pull...<br>Pardon, vous attendiez une autre réponse peut-être ?"),
    "bourgogne"         => array(20,         "Ok on avance..."),
); 

// liste des réponses toutes faites pour les mauvais mots de passe qui ne sont pas ci-dessus
$wrong = array (
    "Désolé, ce n'est pas la bonne réponse :(",
    "Oups, raté !",    
    "Sacrée imagination... mais ce n'est pas ça.",    
    "Raté, mais continuez de chercher !",        
    "Non... essayez autre chose ?",    
    "Non, je ne pense pas.",    
    "Ce n'est pas vraiment ça...",    
);

?>